name: Build and Push
run-name: ${{ github.actor }} building blog and pushing
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '20.10.0'
      - name: Node Install
        run: npm ci
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Node Build
        run: node builder.js
